---
# tasks file for install_package
- name: Install EPEL repository
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Install Midnight Commander
  ansible.builtin.yum:
    name: mc
    state: present

- name: Telepítse az LVM csomagokat
  yum:
    name:
      - lvm2
    state: present

- name: Telepítse az ansible csomagokat
  yum:
    name:
      - ansible
    state: present
