---
- name: Install EPEL repository
  ansible.builtin.yum:
    name: "{{ epel_package }}"
    state: present

- name: Install Midnight Commander
  ansible.builtin.yum:
    name: "{{ mc_package }}"
    state: present

- name: Install LVM packages
  yum:
    name:
      - "{{ lvm_package }}"
    state: present

- name: Install Ansible Packages
  yum:
    name:
      - "{{ ansible_package }}"
    state: present
