- name: create partition
  parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present
    part_end: 15GB

- name: Install lvm2 dependency
  package:
    name: lvm2
    state: present

- name: Extend cache volume group with /dev/sdb1
  lvg:
    vg: cachevg
    state: present
    pvs: /dev/sdb1
  become: true

- name: Create cache pool on cachevg
  lvol:
    vg: cachevg
    lv: cachelv_data
    size: 10g
    state: present
  become: true

- name: Convert cache pool to thin pool type
  command: >
    lvconvert --type thin-pool cachevg/cachelv_data -y
  become: true

- name: Create cache thin pool on cachelv_data
  lvol:
    vg: cachevg
    lv: cachelv_data_thinpool
    thinpool: cachelv_data
    size: 8g
    state: present
  become: true

- name: Create main logical volume on cachevg
  lvol:
    vg: cachevg
    lv: slow
    size: 3g
    state: present
  become: true

- name: Create cache logical volume on cachevg
  lvol:
    vg: cachevg
    lv: cachelv
    thinpool: cachelv_data
    size: 2g
    state: present
  become: true