---
# tasks file for ssh_key_gen
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    
- name: Generate SSH key
  become: true
  openssh_keypair:
    path: ~/.ssh/id_rsa
    type: rsa
    size: 4096
    state: present
    force: no