---
# tasks file for mount_by_UUID
- name: Create mount directory if it doesn't exist
  file:
    path: "{{ mount_path }}"
    state: directory
  become: true

- name: Get UUID of cache disk
  command: blkid -s UUID -o value /dev/sdb1
  register: cache_disk_uuid

- name: Add cache disk to fstab
  mount:
    path: /data/speci/dir
    src: UUID={{ cache_disk_uuid.stdout }}
    fstype: ext4
    opts: defaults
    state: present